version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:ap-south-1:779846808506:task-definition/tutus-pizza-task:14
        LoadBalancerInfo:
          ContainerName: tutus-pizza-container
          ContainerPort: 80